docs: add nocloud documentation
siderolabs/talos pull request #4377
Opened 2021-10-14 19:06 UTC by sergelogvinov

Update documentation - how to use nocloud platform.

Close #4354

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4377)

2022-01-08 19:18 UTC, sergelogvinov commented on website/content/docs/v0.13/Cloud Platforms/nocloud.md
> +```
Yep, I've add the screenshot bellow

2022-01-11 11:25 UTC, kurious-diru requested changes

2022-01-11 11:25 UTC, kurious-diru commented on website/content/docs/v0.13/Cloud Platforms/nocloud.md
> +<img src="/images/proxmox-guide/proxmox-smbios.png" width="920px">
wonder if it is easier to identify if it is in a new no-cloud directory

2022-01-11 11:25 UTC, kurious-diru commented on website/content/docs/v0.13/Cloud Platforms/nocloud.md
> +The Proxmox stores the VM config here /etc/pve/qemu-server/$ID.conf (```$ID``` - VM ID number of virtual machine), you will see someting like:
```suggestion
The Proxmox stores the VM config at /etc/pve/qemu-server/$ID.conf (```$ID``` - VM ID number of virtual machine), you will see something like:
```

2022-01-11 11:25 UTC, kurious-diru commented on website/content/docs/v0.13/Cloud Platforms/nocloud.md
> +Talos can also get machine config from local storage without running a network services (DHCP/HTTP).
```suggestion
Talos can also get machine config from local storage without running network services (DHCP/HTTP).
```

2022-01-11 11:25 UTC, kurious-diru commented on website/content/docs/v0.13/Cloud Platforms/nocloud.md
> +Edit the config file as follows, substituting your own infomation as necessary:
```suggestion
Edit the cloud-init config information in proxmox as follows,  substitute your own information as necessary:
```

2022-01-11 17:36 UTC, kurious-diru approved these changes

2022-01-11 17:49 UTC, smira commented
/ok-to-test

2022-01-11 18:11 UTC, Born2Bake commented
I noticed that when you do something within network.interfaces, talos overwrites settings set in ipconfig0 therefore, it erases networking settings in cloud-init. Thus, if you need to set vip ip address, talos erases settings set in cloud-init ipconfig0 

:disappointed:

```
  network:
    hostname: "${hostname}"
    interfaces:
      - interface: eth0
        addresses:
          - ${ipv4_local}/24
        routes:
          - network: 0.0.0.0/0
            gateway: ${gateway}
        vip:
          ip: ${ipv4_vip}
```

2022-01-11 18:38 UTC, smira commented
> I noticed that when you do something within network.interfaces, talos overwrites settings set in ipconfig0 therefore, it erases networking settings in cloud-init. Thus, if you need to set vip ip address, talos erases settings set in cloud-init ipconfig0

#4755 should actually address that, Talos will stop patching machine configuration

2022-01-12 15:18 UTC, smira approved these changes

2022-01-12 15:43 UTC, smira commented
/m

2022-01-12 15:47 UTC, smira commented
/m

2022-01-12 15:48 UTC, merged