fix: table align hosts file
siderolabs/talos pull request #5663
Opened 2022-05-28 15:30 UTC by sergelogvinov

Cosmetic fix, 
align records by ipv4-string size.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5663)

2022-05-29 06:16 UTC, frezbo approved these changes

2022-05-29 06:17 UTC, frezbo commented
/ok-to-test

2022-05-31 16:21 UTC, smira commented on internal/app/machined/pkg/controllers/network/etcfile.go
> +{{ printf "%-15s" .IP }} {{ .Hostname }} {{ if ne .Hostname .Alias }}{{ .Alias }}{{ end }}
this probably only handles the case with IPv4 addresses though? 

we could also use https://pkg.go.dev/text/tabwriter to produce nice looking file always?

2022-05-31 17:41 UTC, smira commented on internal/app/machined/pkg/controllers/network/etcfile.go
> +{{ printf "%-15s" .IP }} {{ .Hostname }} {{ if ne .Hostname .Alias }}{{ .Alias }}{{ end }}
I refactored to use `tabwriter`

2022-05-31 17:56 UTC, frezbo approved these changes

2022-05-31 17:59 UTC, rsmitty approved these changes

2022-05-31 17:59 UTC, Unix4ever approved these changes

2022-05-31 18:14 UTC, smira commented on internal/app/machined/pkg/controllers/network/etcfile.go
> +	tabW := tabwriter.NewWriter(&buf, 0, 0, 1, ' ', 0)
I think if we add nolint on top, we might ignore more than we need to ignore... so I prefer to explicitly ignore the ones which we know shouldn't fail

2022-05-31 18:17 UTC, DmitriyMV commented on internal/app/machined/pkg/controllers/network/etcfile.go
> +	tabW := tabwriter.NewWriter(&buf, 0, 0, 1, ' ', 0)
I think `//nolint` directives are supposed to be exceptions, not norm. Either way, I don't have any hard opinion on that.

2022-05-31 18:19 UTC, smira commented on internal/app/machined/pkg/controllers/network/etcfile.go
> +	tabW := tabwriter.NewWriter(&buf, 0, 0, 1, ' ', 0)
yeah, I wish it would accept something like `_, _ = tabW.Write()`, but that still triggers the linter

2022-05-31 18:22 UTC, smira commented on internal/app/machined/pkg/controllers/network/etcfile.go
> +	tabW := tabwriter.NewWriter(&buf, 0, 0, 1, ' ', 0)
refactored to use sub-function `write`, this looks better

2022-05-31 18:33 UTC, DmitriyMV requested changes
5 min, I have a suggestion!

2022-05-31 18:41 UTC, smira commented
/m

2022-05-31 18:41 UTC, merged