VMware: Use network information from guestinfo.metadata
siderolabs/talos pull request #6737
Opened 2023-01-13 11:10 UTC by ErikLundJensen

# Pull Request

## What?
This PR is an implementation of #6708  
metadata is loaded from VMware guestinfo and used for configuration of network.

The vmware metadata which is setup by CAPV is defined here:
[VMware metadata](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/pkg/util/constants.go)

The PR implementation is inspired by the [talos nocloud](https://github.com/siderolabs/talos/tree/main/internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud) implementation of metadata and mapping to PlatformNetworkConfig.

## Why? (reasoning)
See #6708 

## Tasks
As this is a draft pull request we have at least the following areas to talk about:

1) Mapping of all elements from metadata to platform network config. See comments `TODO: Not used in this implementation` in [metadata.go](https://github.com/ErikLundJensen/talos/blob/c4f66d06a20d098c1adc3e9eb3a39d71639125a9/internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/metadata.go#L20). Specially the DHCP overrides and Routes requires some work and help from Siderolab maintainers.

2) Read guestinfo.metadata from OVL if available

3) Consider backwards compatibility. Should metadata from guestinfo always be loaded?

## Acceptance

Please use the following checklist:

- [x] you linked an issue (if applicable)
- [x] you included tests (if applicable). -- only added test of unmarshalling yaml from. More test cases could be added.
- [ ] you ran conformance (`make conformance`)
- [ ] you formatted your code (`make fmt`)
- [ ] you linted your code (`make lint`)
- [ ] you generated documentation (`make docs`)
- [ ] you ran unit-tests (`make unit-tests`)

> See `make help` for a description of the available targets.

2023-01-16 12:52 UTC, smira commented on internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/metadata.go
> +	WaitOnNetwork struct {														// TODO: Not used in this implementation
Talos doesn't block on network, it will reconfigure itself as network information becomes available

2023-01-16 12:53 UTC, smira commented on internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/metadata.go
> +	InstanceId    string `yaml:"instance-id"`						// TODO: Not used in this implementation
can be used in `PlatformMetadata` if needed

2023-01-16 12:53 UTC, smira commented on internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/metadata.go
> +	LocalHostname string `yaml:"local-hostname"`				// TODO: Not used in this implementation
what is that? just the hostname? it can be injected

2023-01-16 12:54 UTC, smira commented on internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/metadata.go
> +					RouteMetric: 1024,
looks like there's `RouteMetric` in `DHCPOverrides`

2023-01-16 12:55 UTC, smira commented on internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/testdata/metadata-v2.yaml
> +        macaddress: "00:50:56:b1:81:72"
we could also match on MAC address, Equinix Metal should have an example of doing so

2023-01-16 12:56 UTC, smira commented on internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/testdata/expected-v2.yaml
> +      gateway4: "192.168.0.1"
same files?

2023-01-16 12:56 UTC, smira commented on internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/testdata/expected-v2.yaml
> +      gateway4: "192.168.0.1"
we usually test on the built platform network config

2023-01-25 11:36 UTC, ErikLundJensen commented
Got some violations while running `make link`, however, those files are imports. How to get around this?

```
#0 7.648 internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_amd64.go:18: File is not `gci`-ed with --skip-generated -s standard,default,prefix(github.com/siderolabs/talos) (gci)
#0 7.648 	yaml "gopkg.in/yaml.v3"
#0 7.648 
#0 7.648 internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_amd64.go:24: File is not `gci`-ed with --skip-generated -s standard,default,prefix(github.com/siderolabs/talos) (gci)
#0 7.648 	"github.com/vmware/vmw-guestinfo/vmcheck"
#0 7.648 internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_test.go:12: File is not `gci`-ed with --skip-generated -s standard,default,prefix(github.com/siderolabs/talos) (gci)
#0 7.648 
#0 7.648 internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_test.go:17: File is not `gci`-ed with --skip-generated -s standard,default,prefix(github.com/siderolabs/talos) (gci)
#0 7.648 	"github.com/cosi-project/runtime/pkg/state"
#0 7.648 	"github.com/cosi-project/runtime/pkg/state/impl/inmem"
#0 7.648 	"github.com/cosi-project/runtime/pkg/state/impl/namespaced"
```

2023-01-25 13:21 UTC, ErikLundJensen commented
I have just tested with the lastest from main. The result is now that node names in Kubernetes gets the hostname.
For example, where cluster name is "vmware-test". The local hostname is taken from the GuestInfo Metadata in
[metadata.go](https://github.com/ErikLundJensen/talos/blob/e4d4ba3b3160896f549786efbe254ab957f9c0a1/internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/metadata.go#L249)

I wonder if that is due to my change or some other code change related to naming of Kubernetes nodes in main branch.

New names compared to the old names of the format "talos-xxx-yyy":
```
NAME                                   STATUS   ROLES           AGE     VERSION
vmware-test-controlplane-8dnmg         Ready    control-plane   51m     v1.26.1
vmware-test-controlplane-gccpb         Ready    control-plane   13m     v1.26.1
vmware-test-controlplane-tv57x         Ready    control-plane   32m     v1.26.1
vmware-test-workers-84646885cc-7ssvs   Ready    <none>          10m     v1.26.1
vmware-test-workers-84646885cc-ftdbj   Ready    <none>          5m54s   v1.26.1
vmware-test-workers-84646885cc-sln4w   Ready    <none>          8m1s    v1.26.1
```

2023-03-07 14:21 UTC, frezbo commented on internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/metadata.go
> +// ApplyNetworkConfigV2 data GuestInfo and applies to the Talos runtime platform network configuration.
```suggestion
// ApplyNetworkConfigV2 gets GuestInfo and applies to the Talos runtime platform network configuration.
```

2023-03-07 14:24 UTC, frezbo requested changes
Please remove the `[.DS_Store](https://github.com/siderolabs/talos/pull/6737/files#diff-e2eb93a61ffd7877ea5c751abcb3a618e8e2e9a2073a27f66d4114fe10819f86)` file

2023-03-09 12:18 UTC, smira commented
I'm going to do some small cleanups and testing for your PR @ErikLundJensen and I will get it ready to be merged. Thanks for your contribution!

2023-03-09 12:51 UTC, smira approved these changes

2023-03-09 13:01 UTC, smira approved these changes

2023-03-09 13:16 UTC, merged