fix: allow `talosctl cp` to handle special files in `/proc`
siderolabs/talos pull request #7116
Opened 2023-04-20 18:38 UTC by smira

There is some refactoring to simplify things, but mostly handle files which report size 0 in `stat`, but actually contain data when read.

We try to read up to the small buffer, if we read whole file, we use that as contents, otherwise we still skip the file, as we need to write tar header with size _before_ we read the whole file.

2023-04-20 20:39 UTC, utkuozdemir approved these changes

2023-04-21 00:44 UTC, DmitriyMV requested changes
So I took a stub of actually implementing this covering all corner cases. It should probably look something like this (with all changes applied):

```go
//nolint:gocyclo
func processFile(ctx context.Context, tw *tar.Writer, fi FileItem, buf []byte) error {
	header, err := tar.FileInfoHeader(fi.FileInfo, fi.Link)
	if err != nil {
		// not supported by tar
		return err
	}

	header.Name = fi.RelPath
	if fi.FileInfo.IsDir() {
		header.Name += string(os.PathSeparator)
	}

	skipData := false

	switch header.Typeflag {
	case tar.TypeLink, tar.TypeSymlink, tar.TypeChar, tar.TypeBlock, tar.TypeDir, tar.TypeFifo:
		// no data for these types, move on
		skipData = true
	}

	var r readByteReader

	if !skipData {
		var f *os.File

		f, err = os.Open(fi.FullPath)
		if err != nil {
			return err
		}

		defer f.Close() //nolint:errcheck

		r = bufio.NewReader(f)
	}

	if !skipData && header.Size == 0 {
		// Linux reports /proc files as zero length, but they might have data,
		// so we try to read limited amount of data from it to determine the size
		var n int

		n, err = readFull(r, buf)

		switch {
		case n == 0 && errors.Is(err, io.EOF):
			// file is empty for real
			skipData = true
		case n > 0 && errors.Is(err, io.EOF):
			header.Size = int64(n)
			r = bytes.NewReader(buf[:n])
		case err != nil:
			// error reading from the file
			if errors.Is(err, syscall.EINVAL) {
				// some files are not supported by os.Open, e.g. /proc/sys/net/ipv4/conf/all/accept_local
				skipData = true
			} else {
				return err
			}
		default:
			// none matched so the file is bigger than we expected, ignore it and copy as zero size
			skipData = true
		}
	}

	err = tw.WriteHeader(header)
	if err != nil {
		return err
	}

	if skipData {
		return nil
	}

	return archiveFile(ctx, tw, fi, r)
}

type readByteReader interface {
	io.Reader
	io.ByteReader
	UnreadByte() error
}

// readFull is a wrapper around io.ReadFull that returns io.EOF instead of io.ErrUnexpectedEOF.
// It also performs an additional read (which it will revert) to check for io.EOF.
func readFull(r readByteReader, buf []byte) (int, error) {
	n, err := io.ReadFull(r, buf)
	if errors.Is(err, io.ErrUnexpectedEOF) {
		return n, io.EOF
	} else if err != nil {
		return n, err
	}

	// Perform an additional read to check for io.EOF
	_, err = r.ReadByte()
	if err != nil {
		return n, err
	}

	// Unread the byte we just read
	err = r.UnreadByte()
	if err != nil {
		return n+1, err
	}

	return n, nil
}

func archiveFile(ctx context.Context, tw io.Writer, fi FileItem, r io.Reader) error {
	// Short buffer will be created on stack. The max size on stack, IIRC is around 64KiB.
	var buf [4096]byte

	for {
		n, err := r.Read(buf[:])
		if err != nil {
			if !errors.Is(err, io.EOF) {
				return err
			}

			// EOF with no data to write.
			if n == 0 {
				return nil
			}
			// Reached EOF but still have some data to write.
		}

		select {
		case <-ctx.Done():
			return ctx.Err()
		default:
		}

		_, err = tw.Write(buf[:n])
		if err != nil {
			if err == tar.ErrWriteTooLong {
				log.Printf("ignoring long write for %q", fi.FullPath)

				return nil
			}

			return err
		}
	}
}
```

2023-04-21 11:31 UTC, smira commented on pkg/archiver/tar.go
> +			skipData = true
we are reading from Linux files, not really any random Reader, and they behave pretty consistent way - `io.EOF` is reported on the read beyond EOF.

2023-04-21 11:33 UTC, smira commented on pkg/archiver/tar.go
> +			r = bytes.NewReader(buf[:n])
This case is only for files which report zero length, not for any file, these are special files in `/proc`, and they return data in the first `read()` call, there can't be any buffering whatsoever. In fact `read()` materializes data.

I agree that probably reusing the buf is not fun, I can add a copy.

2023-04-21 11:33 UTC, smira commented on pkg/archiver/tar.go
>  			if err == io.EOF {
actually, no `io.EOF` is the exception that it is never wrapped. both ways work

2023-04-21 12:02 UTC, DmitriyMV reviewed
Attempt to drop "request for changes".

2023-04-21 12:12 UTC, DmitriyMV approved these changes
Dropping "request for changes" doesn't work, so I can't remove it - I can only approve.

The logic seems solid, I'm a bit worried that special cases do not have any tests and we rely on observed, but not documented semantics. Maybe it makes sense to document them, if in future someone decide to update this parts of code.

2023-04-21 12:15 UTC, DmitriyMV commented on pkg/archiver/tar.go
> +			r = bytes.NewReader(buf[:n])
What was the reason for passing this buffer? The [4096]byte slice should be allocated on stack, so it should be relatively cheap if not called in a hot loop.

2023-04-21 12:20 UTC, DmitriyMV commented on pkg/archiver/tar.go
> +			skipData = true
I agree, but the function down below doesn't so that caught my eye.

2023-04-21 12:46 UTC, smira commented
> Maybe it makes sense to document them, if in future someone decide to update this parts of code.

I actually added the test reading from `/proc/self` (which is the easiest always available in the unit-test), and it covers reading from files reported as zero-size, but not actually zero size.

2023-04-21 12:54 UTC, smira commented on pkg/archiver/tar.go
> +			r = bytes.NewReader(buf[:n])
The only reason is to re-use a single buffer for all files, to allocate less in general.

2023-04-24 06:17 UTC, frezbo approved these changes

2023-04-24 12:24 UTC, merged